/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesNewRouteImport } from './routes/games.new'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as NotesMatchupsIndexRouteImport } from './routes/notes.matchups.index'
import { Route as NotesMapsIndexRouteImport } from './routes/notes.maps.index'
import { Route as NotesCivsIndexRouteImport } from './routes/notes.civs.index'
import { Route as NotesMapsSlugRouteImport } from './routes/notes.maps.$slug'
import { Route as NotesCivsSlugRouteImport } from './routes/notes.civs.$slug'
import { Route as NotesMatchupsMyCivOppCivRouteImport } from './routes/notes.matchups.$myCiv.$oppCiv'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesMatchupsIndexRoute = NotesMatchupsIndexRouteImport.update({
  id: '/notes/matchups/',
  path: '/notes/matchups/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesMapsIndexRoute = NotesMapsIndexRouteImport.update({
  id: '/notes/maps/',
  path: '/notes/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesCivsIndexRoute = NotesCivsIndexRouteImport.update({
  id: '/notes/civs/',
  path: '/notes/civs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesMapsSlugRoute = NotesMapsSlugRouteImport.update({
  id: '/notes/maps/$slug',
  path: '/notes/maps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesCivsSlugRoute = NotesCivsSlugRouteImport.update({
  id: '/notes/civs/$slug',
  path: '/notes/civs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesMatchupsMyCivOppCivRoute =
  NotesMatchupsMyCivOppCivRouteImport.update({
    id: '/notes/matchups/$myCiv/$oppCiv',
    path: '/notes/matchups/$myCiv/$oppCiv',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/games/': typeof GamesIndexRoute
  '/notes/civs/$slug': typeof NotesCivsSlugRoute
  '/notes/maps/$slug': typeof NotesMapsSlugRoute
  '/notes/civs/': typeof NotesCivsIndexRoute
  '/notes/maps/': typeof NotesMapsIndexRoute
  '/notes/matchups/': typeof NotesMatchupsIndexRoute
  '/notes/matchups/$myCiv/$oppCiv': typeof NotesMatchupsMyCivOppCivRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/games': typeof GamesIndexRoute
  '/notes/civs/$slug': typeof NotesCivsSlugRoute
  '/notes/maps/$slug': typeof NotesMapsSlugRoute
  '/notes/civs': typeof NotesCivsIndexRoute
  '/notes/maps': typeof NotesMapsIndexRoute
  '/notes/matchups': typeof NotesMatchupsIndexRoute
  '/notes/matchups/$myCiv/$oppCiv': typeof NotesMatchupsMyCivOppCivRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/new': typeof GamesNewRoute
  '/games/': typeof GamesIndexRoute
  '/notes/civs/$slug': typeof NotesCivsSlugRoute
  '/notes/maps/$slug': typeof NotesMapsSlugRoute
  '/notes/civs/': typeof NotesCivsIndexRoute
  '/notes/maps/': typeof NotesMapsIndexRoute
  '/notes/matchups/': typeof NotesMatchupsIndexRoute
  '/notes/matchups/$myCiv/$oppCiv': typeof NotesMatchupsMyCivOppCivRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/games/$gameId'
    | '/games/new'
    | '/games/'
    | '/notes/civs/$slug'
    | '/notes/maps/$slug'
    | '/notes/civs/'
    | '/notes/maps/'
    | '/notes/matchups/'
    | '/notes/matchups/$myCiv/$oppCiv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/games/$gameId'
    | '/games/new'
    | '/games'
    | '/notes/civs/$slug'
    | '/notes/maps/$slug'
    | '/notes/civs'
    | '/notes/maps'
    | '/notes/matchups'
    | '/notes/matchups/$myCiv/$oppCiv'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/games/$gameId'
    | '/games/new'
    | '/games/'
    | '/notes/civs/$slug'
    | '/notes/maps/$slug'
    | '/notes/civs/'
    | '/notes/maps/'
    | '/notes/matchups/'
    | '/notes/matchups/$myCiv/$oppCiv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesNewRoute: typeof GamesNewRoute
  GamesIndexRoute: typeof GamesIndexRoute
  NotesCivsSlugRoute: typeof NotesCivsSlugRoute
  NotesMapsSlugRoute: typeof NotesMapsSlugRoute
  NotesCivsIndexRoute: typeof NotesCivsIndexRoute
  NotesMapsIndexRoute: typeof NotesMapsIndexRoute
  NotesMatchupsIndexRoute: typeof NotesMatchupsIndexRoute
  NotesMatchupsMyCivOppCivRoute: typeof NotesMatchupsMyCivOppCivRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/matchups/': {
      id: '/notes/matchups/'
      path: '/notes/matchups'
      fullPath: '/notes/matchups/'
      preLoaderRoute: typeof NotesMatchupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/maps/': {
      id: '/notes/maps/'
      path: '/notes/maps'
      fullPath: '/notes/maps/'
      preLoaderRoute: typeof NotesMapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/civs/': {
      id: '/notes/civs/'
      path: '/notes/civs'
      fullPath: '/notes/civs/'
      preLoaderRoute: typeof NotesCivsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/maps/$slug': {
      id: '/notes/maps/$slug'
      path: '/notes/maps/$slug'
      fullPath: '/notes/maps/$slug'
      preLoaderRoute: typeof NotesMapsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/civs/$slug': {
      id: '/notes/civs/$slug'
      path: '/notes/civs/$slug'
      fullPath: '/notes/civs/$slug'
      preLoaderRoute: typeof NotesCivsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/matchups/$myCiv/$oppCiv': {
      id: '/notes/matchups/$myCiv/$oppCiv'
      path: '/notes/matchups/$myCiv/$oppCiv'
      fullPath: '/notes/matchups/$myCiv/$oppCiv'
      preLoaderRoute: typeof NotesMatchupsMyCivOppCivRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GamesNewRoute: GamesNewRoute,
  GamesIndexRoute: GamesIndexRoute,
  NotesCivsSlugRoute: NotesCivsSlugRoute,
  NotesMapsSlugRoute: NotesMapsSlugRoute,
  NotesCivsIndexRoute: NotesCivsIndexRoute,
  NotesMapsIndexRoute: NotesMapsIndexRoute,
  NotesMatchupsIndexRoute: NotesMatchupsIndexRoute,
  NotesMatchupsMyCivOppCivRoute: NotesMatchupsMyCivOppCivRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
